// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Lm0VbNnqYkZ7f4W6NtBYKZRHW6Z-c9o',
    appId: '1:175417303525:web:d129a8a3f643534a91cf0c',
    messagingSenderId: '175417303525',
    projectId: 'activity-4232c',
    authDomain: 'activity-4232c.firebaseapp.com',
    storageBucket: 'activity-4232c.firebasestorage.app',
    measurementId: 'G-CGRL2YSGPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW2WyjoN2gLGgQE5UJzBhRB5ql83REf9s',
    appId: '1:175417303525:android:47ee5da099e9248191cf0c',
    messagingSenderId: '175417303525',
    projectId: 'activity-4232c',
    storageBucket: 'activity-4232c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcd9CNgYJp5Cz_mA1mGOf6IqdnFCaf6wg',
    appId: '1:175417303525:ios:787b1870f86b08ff91cf0c',
    messagingSenderId: '175417303525',
    projectId: 'activity-4232c',
    storageBucket: 'activity-4232c.firebasestorage.app',
    iosBundleId: 'com.example.activityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcd9CNgYJp5Cz_mA1mGOf6IqdnFCaf6wg',
    appId: '1:175417303525:ios:787b1870f86b08ff91cf0c',
    messagingSenderId: '175417303525',
    projectId: 'activity-4232c',
    storageBucket: 'activity-4232c.firebasestorage.app',
    iosBundleId: 'com.example.activityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Lm0VbNnqYkZ7f4W6NtBYKZRHW6Z-c9o',
    appId: '1:175417303525:web:19270f605f1f138b91cf0c',
    messagingSenderId: '175417303525',
    projectId: 'activity-4232c',
    authDomain: 'activity-4232c.firebaseapp.com',
    storageBucket: 'activity-4232c.firebasestorage.app',
    measurementId: 'G-TQDP438K0M',
  );
}
